name: Release NodeJS package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org/"
          scope: "@rdmr-eu"

      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

      - run: yarn

      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
